version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: circleci/golang:1.14.3

    working_directory: /go/src/github.com/dnozdrin/vowels-coder
    steps:
      - checkout
      - run:
          name: "Setup Environment Variables"
          command: |
            echo "export CODECOV_TOKEN=55930313-e085-47c4-b996-54e2210012c1" >> $BASH_ENV
      - run:
          name: "Create a temp directory for artifacts"
          command: |
            mkdir -p /tmp/artifacts
      - run: go get -v -t -d ./...
      - run: go test -v -coverprofile=coverage.txt -covermode=atomic ./...
      - run: go build
      - store_artifacts:
          path: /tmp/artifacts

      - codecov/upload:
          file: coverage.txt
